#ifndef GLOBEART_SRC_GLOBE_GLOBE_GENERATOR_SAMPLE_POINT_GENERATOR_MOCK_SAMPLE_POINT_GENERATOR_HPP_
#define GLOBEART_SRC_GLOBE_GLOBE_GENERATOR_SAMPLE_POINT_GENERATOR_MOCK_SAMPLE_POINT_GENERATOR_HPP_

#include "../../types.hpp"
#include <gmock/gmock.h>

namespace globe {

class MockSamplePointGenerator {
 public:
    MOCK_METHOD(Point3, generate, ());
};

}

#endif //GLOBEART_SRC_GLOBE_GLOBE_GENERATOR_SAMPLE_POINT_GENERATOR_MOCK_SAMPLE_POINT_GENERATOR_HPP_
